//! cyb-llm — Pure Rust LLM runtime on wgpu
//!
//! Multi-format model loading (ONNX, safetensors, GGUF),
//! Graph IR with fusion passes, pluggable GPU backends.

pub mod ir;
pub mod loader;
pub mod backend;
pub mod hub;
pub mod generate;
pub mod config;
pub mod manifest;
pub mod quantize;
pub mod import;
pub mod cyb_format;

// Deleted: audio.rs, transcribe.rs, weights.rs (see llm/experimental/README.md
// for what lived here). polar_quant + kv_compress moved to llm/experimental/.

/// ONNX protobuf types (generated by prost)
pub mod onnx_proto {
    pub mod onnx {
        include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
    }
}
