//! cyb-llm — Pure Rust LLM runtime on wgpu
//!
//! Multi-format model loading (ONNX, safetensors, GGUF),
//! Graph IR with fusion passes, pluggable GPU backends.

pub mod ir;
pub mod loader;
pub mod backend;
pub mod hub;
pub mod generate;
pub mod audio;
pub mod transcribe;
pub mod config;
pub mod weights;

/// ONNX protobuf types (generated by prost)
pub mod onnx_proto {
    pub mod onnx {
        include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
    }
}
