[build]
  base = "react"
  command = "deno install && deno task build"
  publish = "react/build"

[build.environment]
  NODE_VERSION = "20"
  DENO_VERSION = "v2.1.4"

[[plugins]]
  package = "./netlify/prebuild/"
